<?php
return array(
/*============DEBUG===============*/
	'DB_TYPE'=>'mysql',
	'DB_HOST'=>'localhost',
	'DB_NAME'=>'cool',
	'DB_USER'=>'root',
	'DB_PWD'=>'123456',
	'DB_PORT'=>'3306',
	'DB_PREFIX'=>'',//表前序
/*============DEBUG===============*/
	/*'DB_TYPE'=>'mysql',
	'DB_HOST'=>'localhost',
	'DB_NAME'=>'a0907150347',
	'DB_USER'=>'a0907150347',
	'DB_PWD'=>'32213562',
	'DB_PORT'=>'3306',
	'DB_PREFIX'=>'',//表前序*/
);
?>