<?php
return array(
	'zh'=>array(
		'title'=>'标题',
		'content'=>'内容',
		'description'=>'简述',
		'keyword'=>'关键字',
		'author'=>'作者',
		'cate'=>'分类',
		'create_time'=>'创建时间',
		'update_time'=>'更新时间',
		'release'=>'发布',
		'cancel'=>'取消',
		'reset'=>'重置',	
		'sketch'=>'草稿',
		'trash'=>'回收站',
		'save'=>'储存',
	),
);